# Generated by Django 2.0.13 on 2019-10-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20191002_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='datePublished',
            new_name='date_published',
        ),
    ]
