# Generated by Django 2.0.13 on 2019-10-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20191003_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categ',
        ),
    ]
