# Generated by Django 2.0.13 on 2019-10-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20191003_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categ',
            new_name='title',
        ),
    ]
